apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-retain-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp3
  encrypted: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rama-day19
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-data
  namespace: rama-day19
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-retain-sc
  resources:
    requests:
      storage: 5Gi
