apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "day20-web.fullname" . }}
  labels:
    {{- include "day20-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "day20-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "day20-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: APP_VERSION
              value: {{ .Values.env.APP_VERSION | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
